config/routes.rb
Rails.application.routes.draw do
  get 'top/main'
  resources :products
  root 'top#main'
  resources :cartitems, only:[:new, :create, :destroy]
  resources :carts, only:[:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cartitems
end

app/models/cartitem.rb
class Cartitem < ApplicationRecord
    belongs_to :product
    belongs_to :cart
end

app/models/product.rb
class Product < ApplicationRecord
    has_one :cartitem
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
        def current_cart
            if session[:cart_id]
                cart = Cart.find(session[:cart_id])
            else
                cart = Cart.create
                session[:cart_id] = cart.id
            end
            cart
        end
        helper_method :current_cart
end

app/controllers/cartitems_controller.rb
class CartitemsController < ApplicationController
    def new
        @cartitem = Cartitem.new(product_id: params[:product_id])
    end
    
    def create
        cart = Cartitem.new(
            qty: params[:cartitem][:qty],
            product_id: params[:cartitem][:product_id],
            cart_id: current_cart.id
            )
        cart.save 
        redirect_to root_path
    end
    
    def destroy
        cartitem = Cartitem.find(params[:id])
        cartitem.destroy
        redirect_to cart_path
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def show
        @carts = Cartitem.all
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @products = Product.all
    end
    
    def new
        @product = Product.new
    end
    
    def create
        @product = Product.new(
            name: params[:product][:name],
            price: params[:product][:price])
        if @product.save
            redirect_to root_path
        else
            render new_product_path
        end
    end
    
    def destroy
        product = Product.find(params[:id])
        product.destroy
        redirect_to root_path
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
        redirect_to products_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartitems_helper.rb
module CartitemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/cartitems/new.html.erb
<%= form_for @cartitem, url: {action: :create} do |f| %>
    <p>
        商品名：<%= Product.find(@cartitem.product_id).name %><br>
        価格：<%= Product.find(@cartitem.product_id).price %>円
    </p>
    <%= f.label :qty, '数量は？' %>
    <%= f.text_field :qty %>
    <%= f.hidden_field :product_id %>
    <%= f.submit 'カートに追加' %>
<% end %>

<%= link_to '戻る', root_path %>

app/views/carts/show.html.erb
<% @sum=0 %>
<% @carts.each do |g| %>
    <p>
        商品名：<%= Product.find(g.product_id).name %>,
        価格：<%= a=Product.find(g.product_id).price %>円,
        個数：<%= b=g.qty %>
        <%= link_to 'カートから削除', "/cartitems/#{g.id}", method: :delete %>
    </p>
<% @sum+= a.to_i*b.to_i %>
<% end %>

合計金額 <%= @sum %>円

<%= link_to '戻る', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EX2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<% if flash[:notice] %>
    <%= flash[:notice] %>
<% end %>

商品ページ
<% @products.each do |e| %>
    <p>
        <%= e.name %>
        <%= e.price %>円
        <%= link_to '削除', "/products/#{e.id}", method: :delete %>
        <%= link_to 'カートに追加', new_cartitem_path(product_id: e.id) %>
    </p>
<% end %>

<p>
    商品の登録は<%= link_to 'こちら', new_product_path %><br>
    カートの中身は<%= link_to 'こちら', cart_path(current_cart.id) %>
</p>

app/views/products/new.html.erb
<% if @product.errors.present? %>
    <h3>エラーがあります。</h3>
    <ul>
        <% @product.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for @product, url: {action: :create} do |f| %>
    <%= f.label :name, '商品名' %>
    <%= f.text_field :name %>
    <%= f.label :price, '価格' %>
    <%= f.text_field :price %>
    <%= f.submit '登録' %>
<% end %>

<%= link_to '戻る', root_path %>